CREATE TYPE trivia_category AS ENUM (
  'movies',
  'history',
  'science',
  'state-capitals',
  'sailing',
  'art',
  'sports'
);

CREATE TABLE drivia_questions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    points INTEGER NOT NULL,
    category trivia_category
);

CREATE TABLE drivia_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE drivia_leaderboard (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES drivia_users(id) ON DELETE CASCADE NOT NULL,
    score INTEGER NOT NULL
);


